# helpers.rb
require 'net/http'
require 'json'
require 'logger'

helpers do

  def token_genuine?(token)
    # make a GET request to auth.platform.local/tokens/:token
    # with the ?app-key field (which really should be a signature generated by
    # a private key, so that the matching public key on auth can check it
    app_key = "5555"

    url = URI.parse("http://auth.platform.local/tokens/#{token}?app-key=#{app_key}")
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    data = JSON.parse(res.body)
    if data[:value] == false
      false
    else
      true
    end
  end

end

