development:
  sessions:
    default:
      database: platform_app_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: platform_app_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: platform_app
      hosts:
        - localhost:27017
